Android support
invertase/react-native-apple-authentication pull request #136
Opened 2020-09-10 00:54 UTC by dburdan

It's here!

- Full support for Android
- Cross-platform `AppleButton` component
- Migration guide
- Updated types
- Fresh docs and examples
- Additional explanation for Android setup

I've been running the core of this for several days on Android with no issues thus far, but haven't thoroughly tested any edge cases. Given the importance of user auth stability and this being a breaking change, maybe worth a beta release?

This is a pretty large PR, so if I missed anything or there are any formatting issues, let me know and I'll update it. An extra set of eyes is always appreciated!

2020-09-10 03:52 UTC, mikehardy commented
Very cool! I have a couple of things queued up for review tomorrow, this one should fit in I hope. This might do with a beta yes but also (in the case we beta and it's "crickets" / not much response) if it's sem-ver major and we've done our best, people can always stay on the previous version while we iron out anything that comes up

2020-09-10 11:24 UTC, nastyakitsune commented
Hi guys! It's very cool that you're working on adding the android support, thanks a lot.
Would you mind telling me the approximate time when this PR will be merged & released?

2020-09-10 14:14 UTC, mikehardy commented
@nastyakitsune you can pull the branch and use it now - in fact knowing someone else tested it would be incredibly helpful. I'm just a volunteer here and I have a pile of priorities - I'm hoping to review today but I don't know what I'll find, and I will never make a release date promise on an open source project I volunteer for

2020-09-10 20:57 UTC, mikehardy requested changes
In general this looks great to me, although it may not seem that way as I notice I have 20 review comments pending :sweat_smile:  - I think almost all of them are easily dealt with. I think it's close and I'm excited to get it in

2020-09-10 20:57 UTC, mikehardy commented on README.md
> +- (iOS only) You are using Xcode version `11` or higher. This will allow you to develop using iOS version `13`, the only version possible for authenticating with Apple.
```suggestion
- (iOS only) You are using Xcode version `11` or higher. This will allow you to develop using iOS version `13` and higher, when the APIs for Sign In with Apple became available.
```

2020-09-10 20:57 UTC, mikehardy commented on README.md
> +Version 2 with Android support introduces a few breaking changes with how methods are accessed. If you're upgrading from 1.x, check out the [Migration Guide](docs/MIGRATION.md).
```suggestion
Version 2 added Android support and introduced a few breaking changes with how methods are accessed. Please see the [Migration Guide](docs/MIGRATION.md).
```

2020-09-10 20:57 UTC, mikehardy commented on README.md
> +- For Android support, a couple extra steps are required on your account. Checkout [our guide](docs/ANDROID_EXTRA.md) for more info.
```suggestion
- For Android support, a couple extra steps are required on your Apple developer account. Checkout [our guide](docs/ANDROID_EXTRA.md) for more info.
```

2020-09-10 20:57 UTC, mikehardy commented on README.md
> +    nonce: 'Random nonce value, will be SHA256 hashed before sending to Apple',
I think this should have be concrete

I use and recommend https://github.com/LinusU/react-native-get-random-values so then the example would be to create a typed array before configure and populate with getRandomValues then use it for the nonce?

2020-09-10 20:57 UTC, mikehardy commented on README.md
> +    redirectUri: 'https://example.com/auth/callback',
What does that redirectUri do? is this (for example - potentially a firebase auth end point? or cloud function that runs? or some other integration?) - the more prescriptive the code + docs, the fewer confused developers will file issues later :sweat_smile:

2020-09-10 20:57 UTC, mikehardy commented on README.md
> +   - Keep in mind you can always access the email server-side by inspecting the `id_token` returned from Apple when verifying the user.
```suggestion
   - Keep in mind you can always access the `email` property server-side by inspecting the `id_token` returned from Apple when verifying the user.
```

2020-09-10 20:57 UTC, mikehardy commented on android/build.gradle
> +    classpath 'com.android.tools.build:gradle:4.0.0'
```suggestion
    classpath 'com.android.tools.build:gradle:4.0.1'
```

2020-09-10 20:57 UTC, mikehardy commented on android/build.gradle
> +    minSdkVersion 17
react-native is still minSdkVersion 16? But maybe this should be set via a getExtOrDefault as well?

```suggestion
    minSdkVersion 16
```

2020-09-10 20:57 UTC, mikehardy commented on android/build.gradle
> +    vectorDrawables.useSupportLibrary = true
Not sure vectorDrawables is something we need? Is that something's that in this PR? I only see pngs in the example, no svgs or icons in xml?

```suggestion
```

2020-09-10 20:57 UTC, mikehardy commented on android/gradle.properties
> +AppleAuth_targetSdkVersion=28
Why not Kotlin current? Or if 1.4.0 is too crazy, 1.3.70?
Android needs to go to API29 to be used in new apps already (as of August) and for updates as of Nov

```suggestion
AppleAuth_kotlinVersion=1.4.0
AppleAuth_compileSdkVersion=29
AppleAuth_buildToolsVersion=29.0.3
AppleAuth_targetSdkVersion=29
```

2020-09-10 20:57 UTC, mikehardy commented on android/build.gradle
> +  implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
I'm concerned about any values that can't be overridden via getExtOrDefault or similar, and there's no dynamic version in this block

```suggestion
  implementation "androidx.core:core-ktx:1.2.0"
  implementation "androidx.fragment:fragment:1.2.2"
  implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
```

2020-09-10 20:57 UTC, mikehardy commented on android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java
> +        }
This alternate style from probably the same stackoverflow https://stackoverflow.com/questions/2817752/java-code-to-convert-byte-to-hexadecimal avoids the padding issues and sign issues while still being pretty quick

```suggestion
        for (int i=0; i < hash.length; i++){
            hexString.append(Character.forDigit((hash[i] >> 4) & 0xF, 16));
            hextString.append(Character.forDigit((hash[i] & 0xF), 16));
        }
```

2020-09-10 20:57 UTC, mikehardy commented on docs/FIREBASE.md
> +- (iOS only) You are using Xcode version `11` or higher. This will allow you to develop using iOS version `13`, the only version possible for authenticating with Apple.
```suggestion
- (iOS only) You are using Xcode version `11` or higher. This will allow you to develop using iOS version `13` or higher, when the Sign In with Apple APIs first became available.
```

2020-09-10 20:57 UTC, mikehardy commented on docs/FIREBASE.md
> +# v6 iOS example
react-native-firebase v5 is dead, and it's past v6 now, so just remove the version specifier

```suggestion
# iOS example
```

2020-09-10 20:57 UTC, mikehardy commented on docs/MIGRATION.md
> +All exports are now namespaced.
```suggestion
All exports are now namespaced, so to migrate from v1 you need to alter your import statements and how you access the symbols.
```

2020-09-10 20:57 UTC, mikehardy commented on example/android/build.gradle
> +        targetSdkVersion = 28
```suggestion
        buildToolsVersion = "29.0.3"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
```

2020-09-10 20:57 UTC, mikehardy commented on example/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip
```suggestion
distributionUrl=https\://services.gradle.org/distributions/gradle-6.6.1-all.zip
```

2020-09-10 20:57 UTC, mikehardy commented on example/app.android.js
> +        nonce: "Unique, non-repeating nonce value",
similar to above - best to have a truly concrete example here or we'll get all sorts of questions on how to get random values

2020-09-10 20:57 UTC, mikehardy commented on example/app.android.js
> +        clientId: "Your client ID",
If we could be prescriptive about where to get the id like below it would decrease future support:

```suggestion
        clientId: "Your client ID",  // <-- get this client id from ... ?, should look like 'asdfsfdasdfasdf'
```

2020-09-10 20:57 UTC, mikehardy commented on example/app.android.js
> +        redirectUri: "Your redirect URI",
```suggestion
        redirectUri: "Your redirect URI",  // <-- this URI should handle redirect like...do we have an example?
```

2020-09-10 21:15 UTC, dburdan commented on android/build.gradle
> +    vectorDrawables.useSupportLibrary = true
Good catch. This was from the now removed native sign in button implementation.

2020-09-11 05:46 UTC, dburdan commented on README.md
> +    redirectUri: 'https://example.com/auth/callback',
Clarified this across the docs and example app. I also added a troubleshooting step to the readme which hopefully covers the most common `clientId` mistakes.

2020-09-11 05:48 UTC, dburdan commented
I think I got it all in the last 5 commits. Thanks for such a thorough review! Your efforts across the entire React Native community are very much appreciated (and noticed)! 🙏🏼

2020-09-11 10:07 UTC, nastyakitsune commented
> @nastyakitsune you can pull the branch and use it now - in fact knowing someone else tested it would be incredibly helpful. I'm just a volunteer here and I have a pile of priorities - I'm hoping to review today but I don't know what I'll find, and I will never make a release date promise on an open source project I volunteer for

Sure, I'll test it in a couple of days. 

@dburdan is there any limitations for android like for iOS? I mean support for certain versions, etc.

2020-09-11 14:43 UTC, mikehardy commented
After the updates @dburdan made last night post-review, I think it should be same constraints as react-native in general, that is it should be okay with minSdkVersion 16

2020-09-11 14:54 UTC, mikehardy commented
> After the updates @dburdan made last night post-review, I think it should be same constraints as react-native in general, that is it should be okay with minSdkVersion 16

I should note this is an assertion! It is a common / easy-to-make mistake to accidentally use APIs that are not available in the specified minSdkVersion (especially when dealing with WebView's and such, which this android implementation does) so we still need to test it and check all the APIs. Typically "test it and check all the APIs" means "release it and handle the resulting bug when someone sees it crash" but if you have time to test it first or @dburdan noted it worked on an API16 emulator that would be positive affirmation

2020-09-11 15:03 UTC, mikehardy commented
Sorry to be chatty but I'm working on this PR right now in review and need to log findings :sweat_smile: 

I just saw that react-native is moving to an API19 minSdkVersion so while this may work for API16 right now the whole ecosystem is about to trim off support for API16-17-18, so testing those won't be necessary shortly, and for this implementation in particular if there are problems with APIs below 19 I will advocate to just move minSdkVersion for the module up to API19 in anticipation of the ecosystem change

2020-09-11 15:10 UTC, mikehardy commented on example/android/build.gradle
> +        classpath("com.android.tools.build:gradle:3.5.2")
```suggestion
        classpath("com.android.tools.build:gradle:4.0.1")
```

2020-09-11 15:14 UTC, mikehardy requested changes
This looks really good now - I adjusted two more tiny things but can't see much

The only thing left is that it appears all the Xcode docs graphics were removed? That can't be on purpose can it? I didn't see the docs shift to show the Xcode configuration in any other way so I think the Xcode docs should remain?

2020-09-11 16:07 UTC, dburdan commented
Xcode graphics are still present. I optimized them in the same commit that I added new ones, so maybe you're seeing that change?

2020-09-11 16:18 UTC, mikehardy approved these changes
Oh of course - re: the Xcode images - I'm not used to seeing images *change*, so when a saw a sea of red related to the images I just incorrectly assumed they were removed. You are right, only shrunk (a good thing!)

2020-09-11 16:21 UTC, mikehardy commented
Now let me figure out how to do a beta haha - haven't done one here. With my other projects when we have big changes like this I either just release them or beta, and if I beta it's time-limited. I don't have time to test this myself right now so I will do a beta to make it easy for at least 1-2 other people to try it and confirm it's working, then after a week or so if nothing major pops up, I'll release it just to keep things moving. Folks can always delay update or propose follow-ons so I'm not concerned about bugs per se, just ease of testing and getting the work out. Thanks again for doing this!

2020-09-11 16:23 UTC, merged

2020-09-11 17:02 UTC, mikehardy commented
@nastyakitsune this is available now for easy (I hope) testing as 2.0.0-beta.0 - https://github.com/invertase/react-native-apple-authentication/releases/tag/v2.0.0-beta.0

2020-09-12 05:30 UTC, dburdan commented
@nastyakitsune Sorry, I missed your questions earlier. So far I've tested down to API 21 without issue. I'll be doing more thorough testing this weekend, and if any limitations are discovered I will document/fix accordingly.

2020-09-14 19:51 UTC, nastyakitsune commented
@mikehardy @dburdan 
Hi guys! While testing the current master branch, I was not be able to build my project. It seems that @dburdan was using the early release of Kotlin plugin for gradle, because I see the next error: `'find((T) -> Boolean): T?' is only available since Kotlin 1.3.50 and cannot be used in Kotlin 1.3` but latest plugin version is [1.4.10](https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm) 😄

Maybe I'm doing something wrong?

2020-09-14 20:11 UTC, mikehardy commented
I actually requested that change, 1.4.10 just came out I think? but I was thinking in general that it would be fine to use 1.4.x. I'm not really in the Kotlin-Using Community (if you will allow that there is such a thing) so perhaps this is too aggressive? I suppose we should internally use 1.4.10 if there is no default set, but that we shouldn't use 1.4.x features yet?

2020-09-14 23:04 UTC, dburdan commented
@nastyakitsune Which version of Kotlin are you using now, and is it something you can't upgrade?

2020-09-16 21:39 UTC, mikehardy commented
I'd like to release this but I'm unsure on the kotlin thing. Normally I would just say "upgrade your kotlin", but before I do that I want to make sure this isn't foolish and I don't code kotlin normally. Is the 1.4 jump problematic in anyway? And balancing that: is our usage of 1.4 features large enough that changing them would be hard?

2020-09-16 22:34 UTC, dburdan commented
I don't believe any 1.4 specific features are in use. I originally built and tested on Kotlin 1.3.50

2020-09-16 22:42 UTC, mikehardy commented
Ah, that's why - the comment above is specifically about 1.3.50+ features. Well, especially for dev tools I'm generally in favor of moving them forward. I'll let this sit one more day just in case any hollers but then my "release it in a week" timer is up and this thing goes 2.0.0 :-)

2020-09-17 16:55 UTC, nastyakitsune commented
@mikehardy @dburdan 
hello, sorry for late reply. I've tested the android support, everything works perfect, thank you for a such a great work. 
But I've met several tricky moments while testing: 
1. It seems that the kotlin version should be mentioned in docs or migration guide, because app will not be built if it uses version less than 1.5. Now I've upgraded it to 1.4 - all is fine. 
2. I had to increase heap memory used by my project to 8gb (through dexOptions in build.gradle file). I don't really think that it's related to this PR, because the project is quiet large, but maybe you have any thoughts about it? In general it's not critical. 
3. It seems that this version could not be built with node 11. I can run it locally on node 14, but not on CI (node 11). It returns this error: 
`error @typescript-eslint/eslint-plugin@3.5.0: The engine "node" is incompatible with this module. Expected version "^10.12.0 || >=12.0.0". Got "11.10.1"
[16:27:16]error Found incompatible module.`

I've tried to run ci with `yarn install --ignore-engines`, it didn't help. 

It's not a blocker, I suppose, but with previous library version, I didn't met this error. 

All the same, thank you 🙂

2020-09-17 17:01 UTC, mikehardy commented
Thank you for the testing and feedback!

1. I'll do an update that mentions the kotlin version - that is important.

2. The build memory thing happens with large projects, we have to recommend it in another project I maintain here: https://rnfirebase.io/#increasing-android-build-memory - I believe this problem is unrelated to this module though, and is just a standard issue android projects must deal with. We only document it in react-native-firebase because that module itself is incredibly large. This one is not really

3. Node 11 should not be used ever I don't think. It was not an LTS version and is obsolete. Node 10 12 and 14 are currently supported LTS versions, and the error message is prescriptive already, so I'm going to leave that one be

Great to hear the success report. I'll document the kotlin item and then release this thing! 🚀

2020-09-17 17:03 UTC, mikehardy commented
The node schedule, for reference: https://nodejs.org/en/about/releases/

2020-09-17 17:07 UTC, mikehardy commented
kotlinVersion documented https://github.com/invertase/react-native-apple-authentication/commit/d63d383355fb0cd47af2dba69f729f764f61ae87

2020-09-17 17:09 UTC, nastyakitsune commented
@dburdan 
Node 11 - sorry, our fault. It's even a good news for us 😁 

The last thing - I have not noticed request about hide/share email in webview (for android), is it ok? I'm not sure, that Apple supports it.

2020-09-17 17:21 UTC, mikehardy commented
I have no answer on hide/share email in webview for android, sorry :-), maybe @dburdan knows the API surface area better?

And as news: I'm packing up the release for final testing and launch now, should be out as 2.0.0 for real in an hour or so

2020-09-17 17:56 UTC, nastyakitsune commented
The question is closed. Request about hiding/sharing email appears, I just forgot to reset apple account settings 🙃

2020-09-17 21:55 UTC, mikehardy commented
v2.0.0 is live now - thanks @dburdan and @nastyakitsune ! 

Cheers

2020-09-18 08:25 UTC, nastyakitsune commented
> v2.0.0 is live now - thanks @dburdan and @nastyakitsune !
> 
> Cheers

Hi! I see tag 2.0.0 here, but the latest published npm release is 1.0.8 still. Maybe something went wrong during publishing?

2020-09-18 13:59 UTC, mikehardy commented
The package is `@invertase` scoped as it's official npmjs.com name - so it should be this:

- https://www.npmjs.com/package/@invertase/react-native-apple-authentication (which shows v2.0.0)

versus

- https://www.npmjs.com/package/react-native-apple-authentication (which does show 1.0.8 yes, coincidentally a version we have never had, so easy to verify it's not correct https://www.npmjs.com/package/@invertase/react-native-apple-authentication)

2020-09-18 14:12 UTC, mikehardy commented
Annoyingly (for me, because it's my fault) there was a release issue but luckily I believe it was without ill effect. I build from multiple machines and one was slightly out of sync yet nevertheless I issued a build from it :scream: - it had all the important parts but the v2.0.0 tag is going to be on the incorrect commit for eternity.

Regardless, there's a new build coming shortly with a separate fix that will contain everything I intended it to contain

Sorry for any confusion