Support for react-native-macos
invertase/react-native-apple-authentication pull request #268
Opened 2022-03-16 19:32 UTC by asabhaney

This PR makes some minor changes to be able to support this library on native MacOS apps if using Microsoft's [react-native-macos](https://github.com/microsoft/react-native-macos) library.

Note that I made a change to `package.json` that is unrelated to this PR, as it seems there were some changes made in #265 that breaks the installation of this lib (not quite sure why, could be that `yarn pod-install` is not occurring in the `ios` directory).

2022-03-16 19:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-apple-authentication?pullRequest=268) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-apple-authentication?pullRequest=268) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-apple-authentication?pullRequest=268) it.</sub>

2022-03-16 20:16 UTC, mikehardy commented
Oh, I'm excited to see this, thank you! I was waiting to do anything react-native-macos-related until they got 0.66 out but I understand it was released recently, so we have a modern version to try. Give me a little bit of time to review this and make sure it's good, but thanks very much for posting it, I'm excited to collaborate and get it merged

2022-03-16 20:17 UTC, mikehardy commented on ios/RNAppleAuthentication/RNAppleAuthButtonViewManager.m
> +@compatibility_alias RNCPView NSView;
nice trick, going to use that in other areas as needed

2022-03-16 20:26 UTC, mikehardy requested changes
mostly minor stuff, this looks like almost exactly what I'd expect for a macOS port, with the exception that your compatibility alias is much cleaner than throwing IFDEFs around everywhere, nice

2022-03-16 20:26 UTC, mikehardy commented on ios/RNAppleAuthentication/RNAppleAuthButtonViewManager.m
> +    if (@available(iOS 13.2, macOS 10.15, *)) {
This is really subtle, but the added the signup type after initial release, macOS only 10.15.1+ https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidbuttontype/asauthorizationappleidbuttontypesignup?language=objc

```suggestion
    if (@available(iOS 13.2, macOS 10.15.1, *)) {
```

2022-03-16 20:26 UTC, mikehardy commented on ios/RNAppleAuthentication/RNAppleAuthButtonViewManager.m
> +      if (@available(iOS 13.2, macOS 10.15, *)) {
signup added after initial release per above

```suggestion
      if (@available(iOS 13.2, macOS 10.15.1, *)) {
```

2022-03-16 20:26 UTC, mikehardy commented on ios/RNAppleAuthentication/RNAppleAuthButtonViewManager.m
> +      if (@available(iOS 13.2, macOS 10.15, *)) {
```suggestion
      if (@available(iOS 13.2, macOS 10.15.1, *)) {
```

2022-03-16 20:26 UTC, mikehardy commented on ios/RNAppleAuthentication/RNAppleAuthModule.m
> +      @"isSignUpButtonSupported": @available(iOS 13.2, macOS 10.15, *) ? @(YES) : @(NO),
Who is even on 10.15.0? Who knows, but it's the docs :-)

```suggestion
      @"isSignUpButtonSupported": @available(iOS 13.2, macOS 10.15.1, *) ? @(YES) : @(NO),
```

2022-03-16 20:26 UTC, mikehardy commented on package.json
> +    "example:prepare": "cd example && yarn && cd ios && (pod install || true)",
I did this, I don't want to revert it. `pod-install` is definitely my preferred way of installing pods these days.
It's resilient to most of the common causes of users having pod install failures and auto-solves most of them.

What's the root cause of failure here? We need to diagnose it and fix that so we can still use pod-install

2022-03-16 20:26 UTC, mikehardy commented on package.json
> -    "example:ios13": "cd example && yarn run:ios13",
why did you remove that one? I use that target all the time, the ios13 simulator is the only simulator that works, and I frequently don't have a real device around to test when checking things in this repo

2022-03-16 20:26 UTC, mikehardy commented on package.json
> -    "example:ios": "cd example && yarn run:ios",
I don't understand why this line needed to change

2022-03-16 20:26 UTC, mikehardy commented on package.json
> +    "example:android": "cd example && yarn android",
I don't understand why this line needed to change

2022-03-16 20:26 UTC, mikehardy commented on package.json
> +    "example:android": "cd example && yarn android",
I don't see a target for running the example with macos?

2022-03-16 20:37 UTC, asabhaney commented
Thanks for the quick review @mikehardy - I should be able to address all those issues pretty quickly. Good catch on the 10.15.1+ compatibility!

2022-03-16 21:17 UTC, mikehardy commented
Well I did say I was excited to see the PR ;-), I still need to pull it locally and test it though, that'll be the thing that takes time, pulling the PR, making sure the example works etc - we don't have CI for it actually working. Maybe also adding CI to make sure the macos target builds (otherwise you know it'll break at some point...). But once the code is good (and it looked close) that's the big first step. Cheers

2022-03-17 12:10 UTC, mikehardy approved these changes
LGTM - now comes the patience part, I want to pull this and check it locally and see if I can get the example working (or *a* example working, perhaps by shifting to react-native-test-app) and that could take some time.
I can't see any reason why the code here (minus some example changes) wouldn't go in though, stated differently, you should be able to confidently use patch-package to apply these changes locally and I'll commit to notification of some sort (and collaboration) if that becomes not true in the future. And then the next release should just retire the patch

Thanks again for the port!

2022-03-17 12:12 UTC, mikehardy commented
To be more concrete about that I'll actually merge so you can even point to a commit hash if desired, and make any necessary changes as a follow on prior to release

2022-03-17 12:13 UTC, merged

2022-03-17 13:18 UTC, asabhaney commented
Great, thanks @mikehardy! I actually did start working on the Mac example (https://github.com/mother/react-native-apple-authentication/tree/macos-example), which does seems to be working, but ironically I must have broke the iOS example (though I have both iOS & macOS versions working in my own project). I'll circle back to this in the next few days to see if I can fix the example stuff.

2022-03-17 13:34 UTC, mikehardy commented
Hold off on the example just a bit, but thanks for giving it a shot. I'm collaborating with someone in a PR to convert to react-native-test-app in another repo and if it's a winner we may be able to get out if the business of maintaining a test app completely

I maintain so many repos that's a huge 2022 goal of mine so I'm going to pursue this now with this repo as one of the reasons to prioritize it

2022-05-16 18:54 UTC, asabhaney commented
Thanks @mikehardy! Let me know if you'd like any help with the example or tests for macOS :)